# Dependencies
# markdown:            redcarpet
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /weblog/:year/:title.html
# relative_permalinks: true

# Setup
title:               Stephen Mizell
tagline:             'Watching the world go by too quickly'
description:         'I am Stephen Mizell, and this is my personal website.'
url:                 http://smizell.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Stephen Mizell
  url:               https://twitter.com/Stephen_Mizell
  email:             smizell@gmail.com

# Custom vars
version:             1.0.0
